<?php

namespace Database\Seeders;

use App\Models\Campaign;
use Illuminate\Database\Seeder;

class CampaignSeeder extends Seeder
{
    public function run(): void
    {
        $campaigns = [
            [
                'id' => 1001,
                'advertiser_id' => 1,
                'group_id' => 2,
                'name' => 'Summer Brand Awareness — Albania',
                'description' => 'Premium display campaign targeting Albanian market for summer season brand awareness. Focuses on building brand recognition among 18-45 demographic.',
                'format_id' => null,
                'marketing_objective' => 'brand_awareness',
                'campaign_type' => 'cpm',
                'status' => 'active',
                'bid_amount' => 2.5000,
                'daily_budget' => 500.0000,
                'total_budget' => 15000.0000,
                'remaining_budget' => 12450.0000,
                'currency' => 'EUR',
                'start_date' => '2025-03-01 00:00:00',
                'end_date' => '2025-04-30 23:59:59',
                'frequency_cap' => 3,
                'frequency_cap_period' => 'day',
                'targeting_geo' => json_encode(['countries' => ['AL'], 'cities' => ['Tirana', 'Durrës']]),
                'targeting_device' => json_encode(['desktop', 'mobile', 'tablet']),
                'weight' => 5,
                'admin_approved' => true,
            ],
            [
                'id' => 1002,
                'advertiser_id' => 1,
                'group_id' => 3,
                'name' => 'Performance CPC — Kosovo Tech',
                'description' => 'Direct response campaign targeting tech-savvy audience in Kosovo. Optimized for clicks and conversions with competitive CPC bidding.',
                'format_id' => null,
                'marketing_objective' => 'conversions',
                'campaign_type' => 'cpc',
                'status' => 'active',
                'bid_amount' => 0.4500,
                'daily_budget' => 300.0000,
                'total_budget' => 9000.0000,
                'remaining_budget' => 7850.0000,
                'currency' => 'EUR',
                'start_date' => '2025-02-15 00:00:00',
                'end_date' => '2025-05-15 23:59:59',
                'frequency_cap' => 5,
                'frequency_cap_period' => 'day',
                'targeting_geo' => json_encode(['countries' => ['XK'], 'cities' => ['Pristina', 'Prizren']]),
                'targeting_device' => json_encode(['desktop', 'mobile']),
                'weight' => 8,
                'admin_approved' => true,
            ],
            [
                'id' => 1003,
                'advertiser_id' => 1,
                'group_id' => 1,
                'name' => 'Q1 Mobile Video — North Macedonia',
                'description' => 'Mobile-first video advertising campaign in North Macedonia. CPV bidding model optimized for video completion rates.',
                'format_id' => null,
                'marketing_objective' => 'video_views',
                'campaign_type' => 'cpv',
                'status' => 'active',
                'bid_amount' => 0.0800,
                'daily_budget' => 400.0000,
                'total_budget' => 12000.0000,
                'remaining_budget' => 10200.0000,
                'currency' => 'EUR',
                'start_date' => '2025-01-01 00:00:00',
                'end_date' => '2025-03-31 23:59:59',
                'frequency_cap' => 2,
                'frequency_cap_period' => 'day',
                'targeting_geo' => json_encode(['countries' => ['MK'], 'cities' => ['Skopje']]),
                'targeting_device' => json_encode(['mobile']),
                'weight' => 7,
                'admin_approved' => true,
            ],
            [
                'id' => 1004,
                'advertiser_id' => 1,
                'group_id' => 4,
                'name' => 'Retargeting Desktop — Montenegro',
                'description' => 'Desktop retargeting campaign for users who visited but didn\'t convert. Focus on Montenegro market with CPA optimization.',
                'format_id' => null,
                'marketing_objective' => 'conversions',
                'campaign_type' => 'cpa',
                'status' => 'paused',
                'bid_amount' => 5.0000,
                'daily_budget' => 200.0000,
                'total_budget' => 6000.0000,
                'remaining_budget' => 4800.0000,
                'currency' => 'EUR',
                'start_date' => '2025-02-01 00:00:00',
                'end_date' => '2025-04-30 23:59:59',
                'frequency_cap' => 4,
                'frequency_cap_period' => 'week',
                'targeting_geo' => json_encode(['countries' => ['ME']]),
                'targeting_device' => json_encode(['desktop']),
                'targeting_retargeting' => 'MOBILE',
                'weight' => 6,
                'admin_approved' => true,
            ],
            [
                'id' => 1005,
                'advertiser_id' => 1,
                'group_id' => 3,
                'name' => 'Lead Generation — Bosnia Herzegovina',
                'description' => 'B2B lead generation campaign targeting Bosnia and Herzegovina. Optimized for form submissions with CPA bidding.',
                'format_id' => null,
                'marketing_objective' => 'lead_generation',
                'campaign_type' => 'cpa',
                'status' => 'active',
                'bid_amount' => 3.5000,
                'daily_budget' => 350.0000,
                'total_budget' => 10500.0000,
                'remaining_budget' => 9100.0000,
                'currency' => 'EUR',
                'start_date' => '2025-02-10 00:00:00',
                'end_date' => '2025-05-10 23:59:59',
                'frequency_cap' => 3,
                'frequency_cap_period' => 'day',
                'targeting_geo' => json_encode(['countries' => ['BA'], 'cities' => ['Sarajevo', 'Banja Luka']]),
                'targeting_device' => json_encode(['desktop', 'tablet']),
                'weight' => 9,
                'admin_approved' => true,
            ],
            [
                'id' => 1006,
                'advertiser_id' => 1,
                'group_id' => 2,
                'name' => 'Regional Display — Balkans Wide',
                'description' => 'Wide-reaching display campaign across all Balkan markets. Brand awareness objective with broad targeting.',
                'format_id' => null,
                'marketing_objective' => 'reach',
                'campaign_type' => 'cpm',
                'status' => 'active',
                'bid_amount' => 1.8000,
                'daily_budget' => 600.0000,
                'total_budget' => 18000.0000,
                'remaining_budget' => 15300.0000,
                'currency' => 'EUR',
                'start_date' => '2025-03-01 00:00:00',
                'end_date' => '2025-05-31 23:59:59',
                'frequency_cap' => 5,
                'frequency_cap_period' => 'day',
                'targeting_geo' => json_encode(['countries' => ['AL', 'XK', 'MK', 'ME', 'BA', 'RS']]),
                'targeting_device' => json_encode(['desktop', 'mobile', 'tablet']),
                'weight' => 4,
                'admin_approved' => true,
            ],
            [
                'id' => 1007,
                'advertiser_id' => 1,
                'group_id' => 1,
                'name' => 'E-commerce Traffic — Serbia',
                'description' => 'Traffic-focused campaign driving users to e-commerce landing pages in Serbia. CPC model optimized for quality clicks.',
                'format_id' => null,
                'marketing_objective' => 'traffic',
                'campaign_type' => 'cpc',
                'status' => 'active',
                'bid_amount' => 0.3500,
                'daily_budget' => 450.0000,
                'total_budget' => 13500.0000,
                'remaining_budget' => 11700.0000,
                'currency' => 'EUR',
                'start_date' => '2025-02-20 00:00:00',
                'end_date' => '2025-05-20 23:59:59',
                'frequency_cap' => 4,
                'frequency_cap_period' => 'day',
                'targeting_geo' => json_encode(['countries' => ['RS'], 'cities' => ['Belgrade', 'Novi Sad']]),
                'targeting_device' => json_encode(['desktop', 'mobile']),
                'weight' => 7,
                'admin_approved' => true,
            ],
            [
                'id' => 1008,
                'advertiser_id' => 1,
                'group_id' => 5,
                'name' => 'Holiday Special — Winter Campaign',
                'description' => 'Seasonal holiday campaign targeting winter shopping period across Balkans. High budget with aggressive CPM bidding.',
                'format_id' => null,
                'marketing_objective' => 'catalog_sales',
                'campaign_type' => 'cpm',
                'status' => 'completed',
                'bid_amount' => 3.2000,
                'daily_budget' => 800.0000,
                'total_budget' => 24000.0000,
                'remaining_budget' => 0.0000,
                'currency' => 'EUR',
                'start_date' => '2024-12-01 00:00:00',
                'end_date' => '2025-01-15 23:59:59',
                'frequency_cap' => 3,
                'frequency_cap_period' => 'day',
                'targeting_geo' => json_encode(['countries' => ['AL', 'XK', 'MK', 'ME', 'BA', 'RS']]),
                'targeting_device' => json_encode(['desktop', 'mobile', 'tablet']),
                'weight' => 10,
                'admin_approved' => true,
            ],
            [
                'id' => 1009,
                'advertiser_id' => 1,
                'group_id' => 3,
                'name' => 'App Install — Mobile Gaming Albania',
                'description' => 'Mobile app install campaign targeting gaming enthusiasts in Albania. CPA bidding optimized for app downloads.',
                'format_id' => null,
                'marketing_objective' => 'app_installs',
                'campaign_type' => 'cpa',
                'status' => 'active',
                'bid_amount' => 2.0000,
                'daily_budget' => 250.0000,
                'total_budget' => 7500.0000,
                'remaining_budget' => 6400.0000,
                'currency' => 'EUR',
                'start_date' => '2025-02-25 00:00:00',
                'end_date' => '2025-04-25 23:59:59',
                'frequency_cap' => 2,
                'frequency_cap_period' => 'week',
                'targeting_geo' => json_encode(['countries' => ['AL']]),
                'targeting_device' => json_encode(['mobile']),
                'weight' => 8,
                'admin_approved' => true,
            ],
            [
                'id' => 1010,
                'advertiser_id' => 1,
                'group_id' => 2,
                'name' => 'Engagement Campaign — Social Kosovo',
                'description' => 'Social media engagement campaign targeting Kosovo audience. CPM bidding with engagement optimization.',
                'format_id' => null,
                'marketing_objective' => 'engagement',
                'campaign_type' => 'cpm',
                'status' => 'draft',
                'bid_amount' => 1.5000,
                'daily_budget' => 150.0000,
                'total_budget' => 4500.0000,
                'remaining_budget' => 4500.0000,
                'currency' => 'EUR',
                'start_date' => '2025-03-20 00:00:00',
                'end_date' => '2025-05-20 23:59:59',
                'frequency_cap' => 6,
                'frequency_cap_period' => 'day',
                'targeting_geo' => json_encode(['countries' => ['XK']]),
                'targeting_device' => json_encode(['mobile', 'tablet']),
                'weight' => 5,
                'admin_approved' => false,
            ],
        ];

        // Add campaigns 1011-1030 with simpler data
        for ($i = 1011; $i <= 1030; $i++) {
            $statuses = ['active', 'paused', 'draft', 'pending_review'];
            $types = ['cpm', 'cpc', 'cpa', 'cpv'];
            $objectives = ['brand_awareness', 'reach', 'traffic', 'conversions', 'engagement'];
            $countries = [['AL'], ['XK'], ['MK'], ['ME'], ['BA'], ['RS']];
            $groupIds = [1, 2, 3, 4, 5, null];

            $campaigns[] = [
                'id' => $i,
                'advertiser_id' => 1,
                'group_id' => $groupIds[array_rand($groupIds)],
                'name' => 'Campaign #' . $i,
                'description' => 'Auto-generated demo campaign ' . $i,
                'format_id' => null,
                'marketing_objective' => $objectives[array_rand($objectives)],
                'campaign_type' => $types[array_rand($types)],
                'status' => $statuses[array_rand($statuses)],
                'bid_amount' => rand(50, 500) / 100,
                'daily_budget' => rand(100, 1000),
                'total_budget' => rand(3000, 30000),
                'remaining_budget' => rand(1000, 20000),
                'currency' => 'EUR',
                'start_date' => '2025-03-01 00:00:00',
                'end_date' => '2025-06-30 23:59:59',
                'frequency_cap' => rand(2, 6),
                'frequency_cap_period' => 'day',
                'targeting_geo' => json_encode(['countries' => $countries[array_rand($countries)]]),
                'targeting_device' => json_encode(['desktop', 'mobile']),
                'weight' => rand(1, 10),
                'admin_approved' => (bool)rand(0, 1),
            ];
        }

        foreach ($campaigns as $campaign) {
            Campaign::create($campaign);
        }
    }
}
